### ISSUE TITLE
Score

### ISSUE THREAD

**Issue by JuKu** [opensourcegamedev/SpaceChaos#41]
Maybe we can introduce an score, for example player gets +100 score, if he destroys an enemy shuttle.

**Comment by crykn** [comment]
A feature to score points is definitely necessary because it provides an enormous replay value. We could also connect it with an external API like [gamejolt](http://gamejolt.com/api/doc/game/scores) or [pewn](https://pewn.de/bugtracker/793699-Highscore-Funktion-fuer-die-Pewn-API/) for synching or providing a scoreboard.

**Comment by JuKu** [comment]
@crykn Interesting idea!
Please create an new issue for pewn api! :D

**Comment by SupressWarnings** [comment]
The score could be consisting of the time you survived and the number of enemies you killed. How it is calculated is another question. Maybe with introducing the score we could also add a local saving of the high-scores.

**Comment by JuKu** [comment]
@SupressWarnings Can you suggest an solution for this calculation?
